-- Must create database tp4;

-- Create table of dates with 3 partitions (p0, p1, p2);
CREATE TABLE DATES (
  D_DATEKEY          INTEGER,
  D_DATE             VARCHAR(18) NOT NULL,
  D_DAYOFWEEK        VARCHAR(10) NOT NULL,
  D_MONTH            VARCHAR(9)  NOT NULL,
  D_YEAR             INTEGER     NOT NULL,
  D_YEARMONTHNUM     INTEGER,
  D_YEARMONTH        VARCHAR(7)  NOT NULL,
  D_DAYNUMINWEEK     INTEGER,
  D_DAYNUMINMONTH    INTEGER,
  D_DAYNUMINYEAR     INTEGER,
  D_MONTHNUMINYEAR   INTEGER,
  D_WEEKNUMINYEAR    INTEGER,
  D_SELLINGSEASON    VARCHAR(12) NOT NULL,
  D_LASTDAYINWEEKFL  INTEGER,
  D_LASTDAYINMONTHFL INTEGER,
  D_HOLIDAYFL        INTEGER,
  D_WEEKDAYFL        INTEGER
)
  PARTITION BY RANGE (D_YEAR) (
  PARTITION p0 VALUES LESS THAN (1990),
  PARTITION p1 VALUES LESS THAN (1994),
  PARTITION p2 VALUES LESS THAN (1996),
  PARTITION p3 VALUES LESS THAN (1999)
  );

