-- First Scenario
SET AUTOCOMMIT = 0;
INSERT INTO R VALUES (5, 6);
SAVEPOINT my_save_point_1;
INSERT INTO R VALUES (7, 8);
SAVEPOINT my_save_point_2;
INSERT INTO R VALUES (9, 10);
ROLLBACK TO my_save_point_1;
INSERT INTO R VALUES (11, 12);
COMMIT;
INSERT INTO R VALUES (23, 6);

-- Second Scenario
SET AUTOCOMMIT = 0;
INSERT INTO R VALUES (5, 6);
SAVEPOINT my_save_point_1;
INSERT INTO R VALUES (7, 8);
SAVEPOINT my_save_point_2;
INSERT INTO R VALUES (9, 10);
ROLLBACK TO my_save_point_1;
INSERT INTO R VALUES (11, 12);
COMMIT;
INSERT INTO R VALUES (23, 6);


-- Third Scenario
SET AUTOCOMMIT = 0;
START TRANSACTION;
SAVEPOINT sp1;
INSERT INTO villes VALUES (14000, 'TIARET' , 'TIARET');
SAVEPOINT sp2;
INSERT INTO villes VALUES (14002, 'SOUGEUR' , 'TIARET');
ROLLBACK TO SAVEPOINT sp2;
COMMIT;
SELECT * FROM villes;